name: Check Markdown Links

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at 00:00
  pull_request:          
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:      

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for broken links (internal)
        run: python ./scripts/check_md_links.py --path ./docs

      - name: Check for broken links (external)
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --timeout 30
            --max-retries 3
            --accept 200,204,301,302,429
            'docs/**/*.md'
          fail: true