name: Test MkDocs Build

on:
  push:
    branches:
      - '**'  # This will trigger the workflow for all branches

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material

    - name: Test MkDocs build
      run: mkdocs build
    
    - name: Check for broken links
      run: |
        pip install mkdocs-linkcheck
        exclude_patterns=$(cat exclude_link_patterns.txt | tr '\n' '|' | sed 's/|$//')
        mkdocs-linkcheck -rv ./docs --ext=".md" --exclude="$exclude_patterns" --sync